services:
  web:
    build: .
    ports:
      - "8800:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
  redisinsight:
    image: "redislabs/redisinsight:v2"
    ports:
      - "5540:5540"
    depends_on:
      - redis

volumes:
  redis-data:
